DROP TABLE IF EXISTS DISCORD_USER;
CREATE TABLE DISCORD_USER
(
    DU_ID               VARCHAR(128) PRIMARY KEY NOT NULL COMMENT '디스코드 유저 UID',
    DU_NAME             VARCHAR(256)             NOT NULL COMMENT '디스코드 닉네임',
    DU_BIRTH_YEAR       INTEGER COMMENT '생년',
    DU_PRE_GUILD        VARCHAR(128) COMMENT '이전 길드',
    DU_PRE_LEAVE_REASON MEDIUMTEXT COMMENT '길드 탈퇴 사유',
    DU_PLAYTIME         VARCHAR(256) COMMENT '플레이 시간',
    DU_JOIN_DATE        DATETIME COMMENT '디스코드 가입 날짜',
    DU_EXIT_DATE        DATETIME COMMENT '디스코드 탈퇴 날짜'
) COMMENT '디스코드 유저에 대한 정보';

DROP TABLE IF EXISTS GUILD;
CREATE TABLE GUILD
(
    G_NAME    VARCHAR(128) PRIMARY KEY NOT NULL COMMENT '길드 명',
    G_MAIN_YN VARCHAR(1)               NOT NULL COMMENT '메인 길드 여부',
    G_SUB_YN  VARCHAR(1)               NOT NULL COMMENT '서브 길드 여부'
);

INSERT INTO GUILD (G_NAME, G_MAIN_YN, G_SUB_YN)
VALUES ('픽셀', '1', '0');
INSERT INTO GUILD (G_NAME, G_MAIN_YN, G_SUB_YN)
VALUES ('PIXEL', '0', '1');

DROP TABLE IF EXISTS GUILD_CHARACTER;
CREATE TABLE GUILD_CHARACTER
(
    MC_ID         VARCHAR(128) PRIMARY KEY NOT NULL COMMENT 'UID',
    MC_DISCORD_ID VARCHAR(128)             NOT NULL COMMENT '디스코드 유저 아이디',
    MC_GUILD_NAME VARCHAR(256)             NOT NULL COMMENT '가입된 길드 이름',
    MC_NAME       VARCHAR(256)             NOT NULL COMMENT '캐릭터 이름',
    MC_MAIN_YN    BOOLEAN                  NOT NULL COMMENT '메인 캐릭터 여부',
    MC_SUB_YN     BOOLEAN                  NOT NULL COMMENT '서브 캐릭터 여부'
) COMMENT '길드에 대한 메이플 캐릭터 정보';

DROP TABLE IF EXISTS BLACKLIST_USER;
CREATE TABLE BLACKLIST_USER
(
    BU_ID         VARCHAR(128) PRIMARY KEY NOT NULL COMMENT 'UID',
    BU_DISCORD_ID VARCHAR(128) COMMENT '디스코드 유저 UID',
    BU_REASON     MEDIUMTEXT COMMENT '사유'
) COMMENT '블랙 리스트 정보';

DROP TABLE IF EXISTS MAPLE_NICKNAME_HISTORY;
CREATE TABLE MAPLE_NICKNAME_HISTORY
(
    MCH_ID          VARCHAR(128) PRIMARY KEY NOT NULL COMMENT 'UID',
    MCH_DISCORD_ID  VARCHAR(128)             NOT NULL COMMENT '디스코드 유저 UID',
    MCH_CHANGE_DATE DATETIME                 NOT NULL COMMENT '변경 날짜',
    MCH_BEFORE_NAME VARCHAR(256)             NOT NULL COMMENT '이전 캐릭터 이름',
    MCH_AFTER_NAME  VARCHAR(256)             NOT NULL COMMENT '변경된 캐릭터 이름'
) COMMENT '메이플 캐릭터 정보 변경 이력';



SELECT * FROM DISCORD_USER;